x-service-templates:
  payment-processor: &payment-processor
    image: zanfranceschi/payment-processor:amd64-20250807222453
    networks:
      - app-network
      - payment-processor-db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 10
        window: 5s
      resources:
        limits:
          cpus: "1.5"
          memory: "100MB"

  payment-processor-db: &payment-processor-db
    image: postgres:17-alpine
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0
    networks:
      - payment-processor-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 10
        window: 5s
      resources:
        limits:
          cpus: "1.5"
          memory: "250MB"

services:
  payment-processor-1:
    <<: *payment-processor
    container_name: payment-processor-default
    hostname: payment-processor-default
    environment:
      - TRANSACTION_FEE=0.07
      - RATE_LIMIT_SECONDS=5
      - INITIAL_TOKEN=123
      - DB_CONNECTION_STRING=Host=/var/run/postgresql;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
    ports:
      - 8001:8080
    volumes:
      - postgres-socket-01:/var/run/postgresql
    depends_on:
      - payment-processor-db-1

  payment-processor-db-1:
    <<: *payment-processor-db
    container_name: payment-processor-default-db
    hostname: payment-processor-default-db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-socket-01:/var/run/postgresql

  payment-processor-2:
    <<: *payment-processor
    container_name: payment-processor-fallback
    hostname: payment-processor-fallback
    environment:
      - TRANSACTION_FEE=0.10
      - RATE_LIMIT_SECONDS=5
      - INITIAL_TOKEN=123
      - DB_CONNECTION_STRING=Host=/var/run/postgresql;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
    ports:
      - 8002:8080
    volumes:
      - postgres-socket-02:/var/run/postgresql
    depends_on:
      - payment-processor-db-2

  payment-processor-db-2:
    <<: *payment-processor-db
    container_name: payment-processor-fallback-db
    hostname: payment-processor-fallback-db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-socket-02:/var/run/postgresql

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sidekiq
    command: bundle exec sidekiq -q payments -q default -c 5
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RAILS_ENV=development
    depends_on:
      - redis
      - rails-db
    networks:
      - app-network

  rails-app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rails-app1
    hostname: rails-app1
    command: bash -c "bundle exec rails db:prepare && bundle exec rails s -b 0.0.0.0 -p 3000"
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@rails-db:5432/rails_app
    networks:
      - app-network
    depends_on:
      - rails-db
      - payment-processor-1
      - payment-processor-2

  rails-app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rails-app2
    hostname: rails-app2
    command: bash -c "bundle exec rails db:prepare && bundle exec rails s -b 0.0.0.0 -p 3000"
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@rails-db:5432/rails_app
    networks:
      - app-network
    depends_on:
      - rails-db
      - payment-processor-1
      - payment-processor-2

  rails-app3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rails-app3
    hostname: rails-app3
    command: bash -c "bundle exec rails db:prepare && bundle exec rails s -b 0.0.0.0 -p 3000"
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@rails-db:5432/rails_app
    networks:
      - app-network
    depends_on:
      - rails-db
      - payment-processor-1
      - payment-processor-2

  nginx:
    image: nginx:latest
    ports:
      - "9999:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - rails-app1
      - rails-app2
      - rails-app3
    networks:
      - app-network

  rails-db:
    image: postgres:17-alpine
    container_name: rails-db
    hostname: rails-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rails_app
    volumes:
      - rails-postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "200MB"

networks:
  app-network:
    driver: bridge
  payment-processor-db:
    driver: bridge

volumes:
  postgres-socket-01:
  postgres-socket-02:
  rails-postgres-data: