default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 5
  username: postgres
  password: postgres
  #host: <%= ENV["POSTGRES_HOST"] || "rails-db" %>

development:
  <<: *default
  database: rails_app

test:
  <<: *default
  database: rails_app_test

production:
  <<: *default
  database: rails_app
